In [1]:
import nltk

C:\Users\shivang\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\shivang\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\shivang\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran-win_amd64.dll
  stacklevel=1)


In [2]:
from nltk.corpus import brown

In [5]:
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [6]:
brown.words()

['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', ...]

In [48]:
data = brown.sents(categories = ['adventure'])

In [9]:
data

[['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', '.'], ['He', 'was', 'well', 'rid', 'of', 'her', '.'], ...]

In [10]:
len(data)

4637

In [52]:
" ".join(data[9])

'He found that if he was tired enough at night , he went to sleep simply because he was too exhausted to stay awake .'

In [12]:
# tokenisation

from nltk.tokenize import sent_tokenize,word_tokenize



In [23]:
document = """It was a very good movie. The cast was amazing and I liked the story.
I went to the movie hall to see it."""
sentence = "Google Summer of Code is too OP shivang@google.org"

In [18]:
sents = sent_tokenize(document)
print(sents)

['It was a very good movie.', 'The cast was amazing and I liked the story.', 'I went to the movie hall to see it.']


In [19]:
len(sents)

3

In [24]:
words = word_tokenize(sentence) # also breaks on specail characters

In [25]:
print(words)

['Google', 'Summer', 'of', 'Code', 'is', 'too', 'OP', 'shivang', '@', 'google.org']


In [22]:
print(len(words))

7


In [26]:
# sttop word removal
from nltk.corpus import stopwords

In [30]:
sw = set(stopwords.words('english'))

In [31]:
sw

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [32]:
text = "i am not a very good cricket player".split()
print(text)

['i', 'am', 'not', 'a', 'very', 'good', 'cricket', 'player']


In [33]:
def remove_stopwords(text,stopwords):
    useful = [w for w in text if w not in stopwords]
    return useful
    

In [34]:
useful_words = remove_stopwords(text,sw)
useful_words

['good', 'cricket', 'player']

In [35]:
#tokenising using regex
sent = "My email is gshivay01@gmail.com, please don't spam my inbox"

In [36]:
from nltk.tokenize import RegexpTokenizer

In [37]:
tokenizer = RegexpTokenizer('[a-zA-Z@.]+')
useful = tokenizer.tokenize(sentence)
print(useful)

['Google', 'Summer', 'of', 'Code', 'is', 'too', 'OP', 'shivang@google.org']


In [38]:
# nltk provides us  Porter, Snowball and Stemmers for stemming
from nltk.stem import SnowballStemmer, PorterStemmer,LancasterStemmer

In [39]:
ps = PorterStemmer()

In [41]:
ps.stem('training')

'train'

In [42]:
ps.stem('laughed')

'laugh'

In [44]:
ps.stem('laughing')

'laugh'

In [ ]:
# Snowball Stemmer is multilingual
# Read documentation


In [93]:
# buid our vocabulary
corpus = [
    'Dan Morgan told himself he would forget Ann Turner.',
    'Sometimes he woke up in the middle of the night thinking of Ann, and then could not get back to sleep.',    
    'His plans and dreams had revolved around her so much and for so long that now he felt as if he had nothing .',
    'He found that if he was tired enough at night, he went to sleep simply because he was too exhausted to stay awake.'
]

In [65]:
from sklearn.feature_extraction.text import CountVectorizer

In [78]:
cv = CountVectorizer()

In [67]:
vc = cv.fit_transform(corpus)

In [72]:
vc = vc.toarray()
print(vc)  # the output says that the (index of sentence in corpus/object,index in vocab.) ----- frequancy

[[0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1]
 [1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 1 1 0 0 2 0 0
  0 1 0 1 0 0 2 1 1 0 1 0 0 0 1 0 0 1 0]
 [2 0 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 2 2 1 0 1 1 0 1 0 0 1 0 0 1 1 0 1 1
  0 0 2 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 0 0 1 1 0 0 0 1 0 0 4 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0
  1 1 0 0 1 1 0 0 0 1 2 0 1 0 0 2 1 0 0]]


In [61]:
print(cv.vocabulary_)

{'dan': 9, 'morgan': 27, 'told': 47, 'himself': 21, 'he': 19, 'would': 54, 'forget': 15, 'ann': 1, 'turner': 49, 'sometimes': 39, 'woke': 53, 'up': 50, 'in': 24, 'the': 42, 'middle': 26, 'of': 33, 'night': 29, 'thinking': 44, 'and': 0, 'then': 43, 'could': 8, 'not': 30, 'get': 17, 'back': 6, 'to': 46, 'sleep': 37, 'his': 22, 'plans': 34, 'dreams': 10, 'had': 18, 'revolved': 35, 'around': 2, 'her': 20, 'so': 38, 'much': 28, 'for': 14, 'long': 25, 'that': 41, 'now': 32, 'felt': 13, 'as': 3, 'if': 23, 'nothing': 31, 'found': 16, 'was': 51, 'tired': 45, 'enough': 11, 'at': 4, 'went': 52, 'simply': 36, 'because': 7, 'too': 48, 'exhausted': 12, 'stay': 40, 'awake': 5}


In [69]:
print(vc[2])

  (0, 19)	2
  (0, 0)	2
  (0, 22)	1
  (0, 34)	1
  (0, 10)	1
  (0, 18)	2
  (0, 35)	1
  (0, 2)	1
  (0, 20)	1
  (0, 38)	2
  (0, 28)	1
  (0, 14)	1
  (0, 25)	1
  (0, 41)	1
  (0, 32)	1
  (0, 13)	1
  (0, 3)	1
  (0, 23)	1
  (0, 31)	1


In [94]:
print(len(cv.vocabulary_)) # has 55 unique words

34


In [74]:
numbers = vc[2]

In [75]:
print(numbers)

[2 0 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 2 2 1 0 1 1 0 1 0 0 1 0 0 1 1 0 1 1 0
 0 2 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
# after vc= vc.array(), the length of each sentence becomes 55 i.e length of the corpus

In [76]:
# removing stop words

def myTokenizer(document):
    words = tokenizer.tokenize(document.lower())
    words = remove_stopwords(words,sw)
    return words

In [77]:
myTokenizer('this is a random text')

['random', 'text']

In [95]:
cv = CountVectorizer(tokenizer = myTokenizer)

In [96]:
vc = cv.fit_transform(corpus).toarray()

In [97]:
print(vc)

[[0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1]
 [0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0]
 [1 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 1 0 0]]


In [98]:
len(vc)

4

In [99]:
len(vc[0])

34

In [92]:
cv.vocabulary_

{'dan': 6,
 'morgan': 16,
 'told': 29,
 'would': 33,
 'forget': 11,
 'ann': 1,
 'turner.': 30,
 'sometimes': 25,
 'woke': 32,
 'middle': 15,
 'night': 18,
 'thinking': 27,
 'could': 5,
 'get': 13,
 'back': 4,
 'sleep.': 24,
 'plans': 20,
 'dreams': 7,
 'revolved': 21,
 'around': 2,
 'much': 17,
 'long': 14,
 'felt': 10,
 'nothing': 19,
 '.': 0,
 'found': 12,
 'tired': 28,
 'enough': 8,
 'went': 31,
 'sleep': 23,
 'simply': 22,
 'exhausted': 9,
 'stay': 26,
 'awake.': 3}

In [ ]:
# Explore more things in Tokenizer

In [100]:
cv.fit(['hey how are you'])

C:\Users\shivang\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:507: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"


CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=<function myTokenizer at 0x00000273B3821A60>,
                vocabulary=None)

In [ ]:
# we cannot use fit_tranform on the test-data because we creatte a vocaulary from the training data out of it.
# and we want to test the data on the basis of the vocabulary already built

In [ ]:
# Explore other ways as makingg vocabulary
# Explore unigram/biggggram/ trigram/n-ggram/ tf-idf normalization etc.