In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

C:\Users\shivang\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\shivang\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\shivang\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran-win_amd64.dll
  stacklevel=1)


In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.4.0'

In [4]:
tf.executing_eagerly()

True

In [5]:
# setting up tensorboard for visualising and monitoring the graph easily
from datetime import datetime
import os
import pathlib

t = datetime.utcnow().strftime("%Y%m%d%H%M%S")
log_dir = "tf_logs"
logd = "{}/r{}/".format(log_dir, t)

# Make a directory if it doesnt exist
from pathlib import Path
home = str(Path.home())
logdir = os.path.join(os.sep,home,logd)

if not os.path.exists(logdir):
    os.makedirs(logdir)

In [6]:
logdir

'C:\\Users\\shivang\\tf_logs/r20210104174059/'

In [7]:
# tensorflow tensors
a = tf.constant(2)
b = tf.constant(3)


In [8]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [9]:
b

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [10]:
a.numpy()

2

In [11]:
a+b

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [12]:
a*b

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [13]:
tf.multiply(a,b).numpy()

6

In [14]:
a_matrix = tf.constant([[1,2],[3,4]])
b_matrix = tf.constant([[5,6],[7,8]])
b_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [7, 8]])>

In [15]:
tf.matmul(a_matrix,b_matrix)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [16]:
# since these are constants we can not change the value of them now
# a.asign(8)----> will give an error

In [17]:
print(a_matrix,b_matrix,sep="\n")

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [18]:
# tf.Variable (creates variiable values)
# they are mutable and can be updated for flexibility
var = tf.Variable(3.0)
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [19]:
d = tf.Variable(np.random.randn(3).reshape(3,1))
d

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float64, numpy=
array([[ 1.12845443],
       [-1.89739394],
       [-0.16218732]])>

In [20]:
tf.Variable(np.random.randn(3,3))

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float64, numpy=
array([[ 2.30694222,  1.05237512,  1.14489141],
       [-0.89708489,  1.28917917,  0.21866764],
       [ 1.02181206,  1.43751026, -0.91539427]])>

In [21]:
var.assign(10)
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>

In [22]:
print('original value:', var.numpy())
print('add 1:', var.assign_add(1.).numpy())
print('subtract 5:', var.assign_sub(5.).numpy())

original value: 10.0
add 1: 11.0
subtract 5: 6.0


In [23]:
v = tf.Variable([[3.,3.2],[1.2,2.2]], dtype = tf.float32, name='my_Variable')
print('name  :', v.name)
print('name  :', v.dtype)
print('name  :', v.shape)
print('name  :', v.device)

name  : my_Variable:0
name  : <dtype: 'float32'>
name  : (2, 2)
name  : /job:localhost/replica:0/task:0/device:CPU:0


In [24]:
op1 = tf.add(a,b)
op1

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [25]:
a+b # same as tf.add

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [26]:
v = a+b
u = v+2
w = v*u
z = w*3
z

<tf.Tensor: shape=(), dtype=int32, numpy=105>

In [27]:
#@tf.function is a very useful module that can be used to convert simple python functions into a highly optimized computational graph that can be run on any runtime environment. When we build a model and then train it TensorFlow we can compile the model and optimize the executions.
@tf.function
def func2(a,b):
        z = tf.multiply(a,b, name='z')
        y1 = tf.constant(3, name='3')
        y2 = tf.constant(4)
        w1 = tf.add(z, y1, name='w1')
        w2 = tf.add(z, y2, name='w2')
        
        return(w1+w2)

In [28]:

func2(10, 20)

<tf.Tensor: shape=(), dtype=int32, numpy=407>

In [29]:
@tf.function
def func(a,b):
    with tf.name_scope('first'):
        z = tf.multiply(a,b, name='z')
    with tf.name_scope('second'):
        y1 = tf.constant(3, name='3')
        y2 = tf.constant(4)
        w1 = tf.add(z, y1, name='w1')
        w2 = tf.add(z, y2, name='w2')
        
    return(w1+w2)

In [30]:
func(10,20)

<tf.Tensor: shape=(), dtype=int32, numpy=407>

In [31]:

# Setup a writer to save graph information and TensorFlow logs
# To be displayed with Tensorboard

writer = tf.summary.create_file_writer(logdir)
tf.summary.trace_on()

In [32]:
a = tf.constant(3)
b = tf.constant(4)
func(a,b)
with writer.as_default():
    tf.summary.trace_export(
        name="func2",
        step=0,
        profiler_outdir=logdir)

In [33]:
logdir

'C:\\Users\\shivang\\tf_logs/r20210104174059/'

In [ ]:
!tensorboard --logdir $logdir

In [ ]:
@tf.function 
def g(x):
    y = tf.reduce_sum(x)
    if y > 0:
        return y
    return tf.abs(y)

In [ ]:
print(tf.autograph.to_code(g.python_function))

In [ ]:
#Calculate gradients
#Gradient evaluation is very importnat machine learning because it is based on function optimization. You can use tf.GradientTape() method to record the gradient of an arbitrary function
w = tf.Variable(3.0)

# Gradient scope for the function w^2
with tf.GradientTape() as tape:
    expression = tf.exp(w) + 2 * w +  w * w

grad = tape.gradient(expression, w)
print(f'The gradient of exp at {w.numpy()} is {grad.numpy()}')

In [ ]:
def sigmoid(x):
    return 1/(1 + tf.exp(-x))

In [ ]:
#define a varaible
x = tf.Variable(0.)

#record the gradient
with tf.GradientTape() as tape:
    sig = sigmoid(x)
    
res = tape.gradient(sig, x).numpy()
print('The gradient of the sigmoid function at 0.0 is ', res)