In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_regression
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

C:\Users\shivang\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\shivang\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\shivang\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran-win_amd64.dll
  stacklevel=1)


In [5]:
dataset = pd.read_csv("Salary_Data.csv")

In [6]:
dataset.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [18]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,1].values

In [13]:
# X = dataset.values[:,0]
# y = dataset.values[:,1]

In [14]:
X

array([ 1.1,  1.3,  1.5,  2. ,  2.2,  2.9,  3. ,  3.2,  3.2,  3.7,  3.9,
        4. ,  4. ,  4.1,  4.5,  4.9,  5.1,  5.3,  5.9,  6. ,  6.8,  7.1,
        7.9,  8.2,  8.7,  9. ,  9.5,  9.6, 10.3, 10.5])

In [19]:
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.33, random_state=42)

In [20]:
model = LinearRegression()

In [21]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
model.predict(X_test[:5])

array([115814.30756236,  71511.92534771, 102617.85328566,  75282.34085534,
        55487.65944028])

In [23]:
y_test[:5]

array([112635.,  67938., 113812.,  83088.,  64445.])

In [24]:
model.score(X_test,y_test)

0.9553063138044949

In [32]:
yrs = int(input("How many Years of Experience do you have?"))
sal = model.predict(np.array([yrs]).reshape(-1,1))
print("Your estimated Salary is: $",sal[0])

How many Years of Experience do you have? 12


Your estimated Salary is: $ 138436.80060814234
