In [1]:
import numpy as np

In [3]:
a = np.random.randint(1,10,(2,4))
b = np.random.randint(1,10,(2,4))

In [4]:
a,b

(array([[8, 5, 8, 8],
        [5, 4, 5, 5]]), array([[7, 1, 9, 1],
        [4, 9, 3, 3]]))

In [5]:
a+b

array([[15,  6, 17,  9],
       [ 9, 13,  8,  8]])

In [6]:
# in case both the sizes are unequal, they wont be added
c = np.random.randint(1,10,(4))
d = np.random.randint(1,10,(2,4))

In [7]:
c

array([3, 4, 8, 4])

In [8]:
d

array([[2, 2, 3, 6],
       [8, 7, 5, 6]])

In [9]:
c+d # this is known as bradcasting 

array([[ 5,  6, 11, 10],
       [11, 11, 13, 10]])

In [10]:
l = np.random.randint(1,10,(4,2))
m = np.random.randint(1,10,(2,4))
# l+m wont work

In [ ]:
# rules of broadcasting
# 1) shape shoould be same, start cheking from right to left
# 2) if it has 1 in it, it will work
# 3) if both above are correct and still some elements are left, then it will work